Revert "All methods need to have 'self' as first argument"
This reverts commit 022fb1b7e199f77900ce2150546e54a84f35bfb3.

Broke the code:
Traceback (most recent call last):
  File "/media/lumberyard/bin/convert_external_genome.py", line 95, in <module>
    if __name__ == "__main__": main()
  File "/media/lumberyard/bin/convert_external_genome.py", line 86, in main
    external_nickname = Genome.generate_nickname_from_fasta_filename( commandline_args.external )
TypeError: generate_nickname_from_fasta_filename() missing 1 required positional argument: 'fasta_filename'

I think static methods must not have 'self' as the first argument.

-- David